$deploymentTarget = '11.0'

platform :ios, $deploymentTarget

def source_type
    :tag
end

$sourceValue = '2.9.0.0'

# Pods for DialogDemo
def dialog_demo_pods
    pod 'Dialog', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Notification Service Extension
def notification_service_extension_pods
    pod 'DialogNotificationService', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Share Extension
def share_extension_pods
    pod 'DialogShare', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Notification Content Extension
def notification_content_extension_pods
    pod 'DialogNotificationContent', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Intents Extension
def intents_extension_pods
    pod 'DialogIntents', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

target 'DialogDemo' do
    use_frameworks!

    dialog_demo_pods
end

target 'DialogDemo Notification Service' do
    use_frameworks!

    notification_service_extension_pods
end

target 'DialogDemo Share' do
    use_frameworks!

    share_extension_pods
end

target 'DialogDemo Notification Content' do
    use_frameworks!

    notification_content_extension_pods
end

target 'DialogDemo Intents' do
    use_frameworks!

    intents_extension_pods
end
