$deploymentTarget = '11.0'

platform :ios, $deploymentTarget

$SDKPodsPath = 'git@github.com:dialogs/dialog-swift-platform.git'

def source_type
    :branch
end

$sourceValue = 'pre-release'

# Pods for DialogDemo
def dialog_demo_pods
    pod 'Dialog', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Notification Service Extension
def notification_service_extension_pods
    pod 'DialogNotificationService', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Share Extension
def share_extension_pods
    pod 'DialogShare', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Notification Content Extension
def notification_content_extension_pods
    pod 'DialogNotificationContent', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Intents Extension
def intents_extension_pods
    pod 'DialogIntents', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

target 'DialogDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    dialog_demo_pods
end

target 'DialogDemo Notification Service' do
    use_frameworks!

    notification_service_extension_pods
end

target 'DialogDemo Share' do
    use_frameworks!

    share_extension_pods
end

target 'DialogDemo Notification Content' do
    use_frameworks!

    notification_content_extension_pods
end

target 'DialogDemo Intents' do
    use_frameworks!

    intents_extension_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Dialog-iOS'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] <<  "AS_USE_VIDEO=1"
            end
        end

        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $deploymentTarget
        end
    end
end
