$deploymentTarget = '11.0'

platform :ios, $deploymentTarget

$SDKPodsPath = 'git@github.com:dialogs/dialog-swift-platform.git'
$tempPath = '.temp'

def source_type
    :branch
end

$sourceValue = 'pre-release'

$prebuildFrameworks = false

if $prebuildFrameworks
    plugin 'cocoapods-binary'
end

# Pods for DialogDemo
def dialog_demo_pods
    pod 'DialogCalls-GRPC', :git => 'git@github.com:dialogs/server-api-calls-sdk.git', :tag => '2.19.0'
    pod 'DialogSDK-GRPC', :git => 'https://github.com/dialogs/api-schema.git', :tag => 'v1.69.0'
    pod 'DialogWebRTC', :git => 'git@github.com:dialogs/dialog-webrtc-ios-pod.git', :tag => '27.08.2020-15-07'
    pod 'DLGPicker', :git => 'https://github.com/dialogs/Alerts-Pickers', :tag => '1.0.41'
    pod 'InputBarAccessoryView', :git => 'https://github.com/nathantannar4/InputBarAccessoryView.git', :tag => '5.0.0'
    pod 'RxASDataSources', :git => 'https://github.com/dialogs/RxASDataSources', :tag => '1.0.0.1'
    pod 'RxCocoa-Texture', :git => 'https://github.com/jeffersonsetiawan/RxCocoa-Texture.git', :branch => 'texture3'
    pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '5.2.2'
    pod 'Sodium', :git => 'https://github.com/dialogs/swift-sodium.git', :tag => '0.8.1'
    pod 'Texture', :git => 'https://github.com/dialogs/Texture.git', :tag => '3.0.0.1'
    pod 'XCoordinator/RxSwift', :git => 'https://github.com/quickbirdstudios/XCoordinator', :tag => '2.0.7'

    pod 'Dialog', :git => 'git@github.com:dialogs/oem-ios.git', source_type => $sourceValue
end

# Pods for Notification Service Extension
# def notification_service_extension_pods
#     $extensionsPath = 'DialogExtensions/'
#
#     pod 'DialogAuth', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogNotifications', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogNotificationServiceExtension', :git => $SDKPodsPath, source_type => $sourceValue
# end

# Pods for Share Extension
# def share_extension_pods
#     pod 'RxDataSources', '4.0.1', :inhibit_warnings => true
#     pod 'TrustKit', '1.6.3', :inhibit_warnings => true
#     pod 'Swinject', '2.7.1', :inhibit_warnings => true
#
#     pod 'DialogProtocols', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogMessaging', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogStorage', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogAuth', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogSecureStorage', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogFeatureFlags', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogFiles', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogSwiftGRPCExtra', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogMetrics', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogShareExtension', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogPasscode', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogPasscodeUI', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogNetService', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogSharedComponents', :git => $SDKPodsPath, source_type => $sourceValue
# end

# Pods for Notification Content Extension
# def notification_content_extension_pods
#     pod 'Swinject', '2.7.1', :inhibit_warnings => true
#
#     pod 'DialogNotificationContentExtension', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogStorage', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogSecureStorage', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogAuth', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogSecureStorage', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogNotifications', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogFiles', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogMessaging', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogSharedComponents', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogSwiftGRPCExtra', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogMetrics', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogNetService', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogFeatureFlags', :git => $SDKPodsPath, source_type => $sourceValue
# end

# Pods for Intents Extension
# def intents_extension_pods
#     pod 'Swinject', '2.7.1', :inhibit_warnings => true
#
#     pod 'DialogIntentsExtension', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogStorage', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogSecureStorage', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogAuth', :git => $SDKPodsPath, source_type => $sourceValue
#     pod 'DialogMessaging', :git => $SDKPodsPath, source_type => $sourceValue
# end

target 'DialogDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    if $prebuildFrameworks
        enable_bitcode_for_prebuilt_frameworks!
        all_binary!
    end

    dialog_demo_pods
end

# target 'DialogDemo Notification Service' do
#     use_frameworks!
#
#     if $prebuildFrameworks
#         enable_bitcode_for_prebuilt_frameworks!
#         all_binary!
#     end
#
#     notification_service_extension_pods
#     shared_pods
# end

# target 'DialogDemo Share' do
#     use_frameworks!
#
#     if $prebuildFrameworks
#         enable_bitcode_for_prebuilt_frameworks!
#         all_binary!
#     end
#
#     share_extension_pods
# end

# target 'DialogDemo Notification Content' do
#     use_frameworks!
#
#     if $prebuildFrameworks
#         enable_bitcode_for_prebuilt_frameworks!
#         all_binary!
#     end
#
#     notification_content_extension_pods
# end

# target 'DialogDemo Intents' do
#     use_frameworks!
#
#     if $prebuildFrameworks
#         enable_bitcode_for_prebuilt_frameworks!
#         all_binary!
#     end
#
#     intents_extension_pods
# end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Dialog-iOS'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] <<  "AS_USE_VIDEO=1"
            end
        end

        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $deploymentTarget
        end
    end
end
